# Generated by Django 4.2.1 on 2023-10-17 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifyuserotp',
            name='email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activationtoken', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='verifyuserotp',
            name='otp',
            field=models.CharField(max_length=6, verbose_name='Token'),
        ),
    ]
