# Generated by Django 4.2.1 on 2023-10-17 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_notes_invited_user_notes_owner'),
        ('accounts', '0002_alter_verifyuserotp_email_alter_verifyuserotp_otp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserAccount',
        ),
    ]
