# Generated by Django 4.2.1 on 2023-10-17 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_user_useraccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verifyuserotp',
            old_name='email',
            new_name='user',
        ),
    ]
