# Generated by Django 4.2.1 on 2023-10-17 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_email_verifyuserotp_user'),
        ('main', '0003_notes_invited_user_notes_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='invited_user',
            field=models.ManyToManyField(blank=True, related_name='invited_user', to='accounts.useraccount'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='accounts.useraccount'),
        ),
    ]
